### ISSUE TITLE
Criar função de criação do objeto evento que será enviado para função Update da API, com as informações que serão alteradas

### ISSUE THREAD

**Issue by FlightofIcarus** [FlightofIcarus/MyRoutine#22]

**Comment by lucasPaschoalick** [comment]
- Função presente no commit e501812 na branch feature/21-criar-função-de-criação-do-objeto](https://github.com/FlightofIcarus/MyRoutine/compare/feature/21-criar-fun%C3%A7%C3%A3o-de-cria%C3%A7%C3%A3o-do-objeto)
